name: "Release Action"
description: "Create a GitHub release with assets"

inputs:
  version:
    description: "Release version"
    required: true
  release_notes:
    description: "Release notes"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Extract version from Cargo.toml
      shell: bash
      run: |
        VERSION=$(grep '^version = ' src/YOUR_CANISTER/Cargo.toml | cut -d '"' -f2)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ inputs.version }}
        release_name: Release v${{ inputs.version }}
        body: ${{ inputs.release_notes }}
        draft: false
        prerelease: false
